export const projects = [
  {
    description:
      "A video transcoder that can transcode video to different formats. It uses AWS Lambda, AWS ECS, AWS S3, and Docker to run the transcoding process.",
    opensource: true,
    projectName: "Video Transcoder",
    githubLink: "https://github.com/swarnikaraj/videotranscoder12",
    imageSrc: "/videotranscode.jpg",
    techStacks: [
      "Nextjs",
      "Golang",
      "AWS Lambda",
      "Redis Queue",
      "Redis PubSub",
      "Docker",
      "AWS ECS",
      "Event driven",
    ],
    liveLink: "https://github.com/swarnikaraj/videotranscoder12",
  },
  {
    description:
      "A clone of the Vercel website that build and deploye simple static frontend applications",
    opensource: false,
    projectName: "Vercel Clone",
    githubLink: "https://github.com/swarnikaraj/vercel-clone",
    imageSrc: "/vercel.jpg",
    techStacks: [
      "Nodejs",
      "AWS ECS",
      "Reactjs",
      "Redis",
      "Event driven",
      "Docker",
      "Websocket",
    ],
    liveLink: "https://vercel-clone-lake.vercel.app/",
  },
  {
    opensource: false,
    projectName: "Multi-User Video Calling",
    githubLink: "https://github.com/swarnikaraj/videocall",
    imageSrc: "/videocalling.jpg",
    techStacks: ["WebRTC", "Nodejs", "Reactjs", "Websocket"],
    liveLink: "https://github.com/swarnikaraj/videocall",
  },
  {
    opensource: false,
    projectName: "NFT Minting Dapp",
    githubLink: "https://github.com/swarnikaraj/BBMintNew",
    imageSrc: "/nftapp.jpg",
    techStacks: ["Reactjs", "Solidity", "Ethers.js", "Metamask", "ERC-721A"],
    liveLink: "https://bb-mint-new.vercel.app/",
  },
];
